<div class="container space-2 space-top-md-5 space-top-lg-1">
  <!-- SVG Bottom Shape -->
    <figure>
      <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="64px"
           viewBox="0 0 1921 273" style="margin-bottom: -8px; enable-background:new 0 0 1921 273;" xml:space="preserve">
        <polygon class="fill-gray-100" points="1921,0 0,0 0,273 "/>
      </svg>
    </figure>
    <!-- End SVG Bottom Shape -->

  <h1 class="my-4">Welcome to HealthChain</h1>

  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-6 mb-5">
      <p>By Team Gigamike. Main Features as follows:</p>
      <ul>
        <li>Medical Records Online</li>
        <li>Consultation Online</li>
        <li>Health Care Assistant</li>
      </ul>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt.</p>
    </div>
    <div class="col-lg-6">
      <img class="img-fluid rounded" src="/img/logo.png" alt="">
    </div>
  </div>
  <!-- /.row -->



  <!-- Call to Action Section -->
  <div class="row mb-4">
    <div class="col-md-8">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
    </div>
    <div class="col-md-4">
      <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('registration'); ?>">Registration</a>
    </div>
  </div>

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h4 class="card-header">Medical Records Online</h4>
        <div class="card-body">
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h4 class="card-header">Consultation Online</h4>
        <div class="card-body">
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h4 class="card-header">Health Care Assistant</h4>
        <div class="card-body">
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
        </div>
        <div class="card-footer">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Section -->
  <h2>Doctors</h2>

  <div class="row">
    <?php foreach ($paginator as $row): ?>
    <div class="col-lg-4 mb-4">
      <div class="card h-100 text-center">
        <img class="card-img-top" src="/img/user/<?php echo $row->getId(); ?>/photo-750x450.jpg" alt="">
        <div class="card-body">
          <h4 class="card-title">
            <?php if($row->getGender() == 'f'): ?>
              Dra.
            <?php else: ?>
              Dr.
            <?php endif; ?>
            <?php echo $this->escapeHtml($row->getFirstName()); ?> <?php echo $this->escapeHtml($row->getLastName()); ?></h4>
          <h6 class="card-subtitle mb-2 text-muted"><?php echo $this->escapeHtml($row->getTitle()); ?></h6>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
  <!-- /.row -->

  <hr>

  <!-- Call to Action Section -->
  <div class="row mb-4">
    <div class="col-md-8">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
    </div>
    <div class="col-md-4">
      <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('registration'); ?>">Registration</a>
    </div>
  </div>
</div>

<!-- Testimonials Section -->
    <div class="container space-bottom-1">
      <!-- SVG Quote -->
      <figure class="mx-auto text-center mb-3">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="48px" height="48px"
           viewBox="0 0 8 8" style="enable-background:new 0 0 8 8;" xml:space="preserve">
          <path class="fill-gray-400" d="M3,1.3C2,1.7,1.2,2.7,1.2,3.6c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5
            C1.4,6.9,1,6.6,0.7,6.1C0.4,5.6,0.3,4.9,0.3,4.5c0-1.6,0.8-2.9,2.5-3.7L3,1.3z M7.1,1.3c-1,0.4-1.8,1.4-1.8,2.3
            c0,0.2,0,0.4,0.1,0.5c0.2-0.2,0.5-0.3,0.9-0.3c0.8,0,1.5,0.6,1.5,1.5c0,0.9-0.7,1.5-1.5,1.5c-0.7,0-1.1-0.3-1.4-0.8
            C4.4,5.6,4.4,4.9,4.4,4.5c0-1.6,0.8-2.9,2.5-3.7L7.1,1.3z"/>
        </svg>
      </figure>
      <!-- End SVG Quote -->

      <!-- Blockquote -->
      <div class="w-md-75 text-center mx-md-auto mb-6">
        <blockquote class="lead font-weight-normal">Welcome to HealthChain By Team Gigamike</blockquote>
      </div>
      <!-- End Blockquote -->

      <!-- Reviewer -->
      <div class="d-flex justify-content-center align-items-center w-lg-50 mx-auto">
        <div class="u-avatar">
          <img class="img-fluid rounded-circle" src="/img/chat-logo.jpg" alt="Image Description">
        </div>
        <div class="ml-3">
          <h4 class="h6 mb-0">Mik Galon</h4>
          <small class="text-muted">Gigamike.net</small>
        </div>
      </div>
      <!-- End Reviewer -->
    </div>
    <!-- End Testimonials Section -->

    <!-- SVG Top Shape -->
    <figure>
      <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="64px"
           viewBox="0 0 1921 273" style="margin-bottom: -8px; enable-background:new 0 0 1921 273;" xml:space="preserve">
        <polygon class="fill-gray-100" points="0,273 1921,273 1921,0 "/>
      </svg>
    </figure>
    <!-- End SVG Top Shape -->

    <!-- Contacts Section -->
    <div class="bg-light position-relative">
      <div class="container space-bottom-2">

      </div>
    </div>
    <!-- End Contacts Section -->
